apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: slave
  namespace: orleans
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orleans
      component: slave
  template:
    metadata:
      labels:
        app: orleans
        component: slave
    spec:
      containers:
      - name: slave
        image: wzorgdrager/orleans:0.7
        args:
        - "1"
        - "slave"
        - "1400"
        - "1500"
        - "1501"
        - "1510"
        - "master.orleans"
        - "1400"
        - "1500"
        ports:
        - containerPort: 1400
        - containerPort: 1500
        - containerPort: 1501
        - containerPort: 1502
        - containerPort: 1503
        - containerPort: 1504
        - containerPort: 1505
        - containerPort: 1506
        - containerPort: 1507
        - containerPort: 1508
        - containerPort: 1509
        - containerPort: 1510
    env:
    - name: HOSTNAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
